proto: fix IP_sock() failure issue
Run crashinfo hit below exception:

Traceback (most recent call last):
  File "/usr/lib64/crash/extensions/mpykdump.so/progs/crashinfo.py", line 1648, in <module>
  File "/usr/lib64/crash/extensions/mpykdump.so/progs/crashinfo.py", line 766, in check_network
  File "/root/rpmbuild/BUILD/crash-pykdump-3.1.0/LinuxDump/inet/summary.py", line 50, in TCPIP_Summarize
    pstr = IP_sock(o, True)
  File "/root/rpmbuild/BUILD/crash-pykdump-3.1.0/LinuxDump/inet/proto.py", line 198, in __init__
    self.wmem_alloc = s.wmem_alloc_counter
  File "/root/rpmbuild/BUILD/crash-pykdump-3.1.0/pykdump/wrapcrash.py", line 565, in __getattr__
    raise KeyError(msg)
KeyError: '<struct tcp_sock> does not have a field <wmem_alloc_counter>'

This caused kernel commit 14afee4b60 "net: convert sock.sk_wmem_alloc from
atomic_t to refcount_t" changed sk_wmem_alloc type from atomic_t to
refcount_t, add check when set inet_sock.wmem_alloc_counter to fix this
issue.

Signed-off-by: Joe Jin <joe.jin@oracle.com>