crashinfo: fix print_CFS_runqueue() error
When crashinfo call print_CFS_runqueue it failed with below error:

Traceback (most recent call last):
  File "/usr/lib64/crash/extensions/mpykdump.so/progs/crashinfo.py", line 1644, in <module>
  File "/usr/lib64/crash/extensions/mpykdump.so/progs/crashinfo.py", line 706, in check_runqueues
  File "/usr/lib64/crash/extensions/mpykdump.so/progs/crashinfo.py", line 631, in print_CFS_runqueue
  File "/root/rpmbuild/BUILD/crash-pykdump-3.1.0/pykdump/wrapcrash.py", line 565, in __getattr__
    raise KeyError(msg)
KeyError: '<struct rb_root_cached> does not have a field <rb_node>'

This caused by after upstream commit 2161573ec "sched/deadline: replace
earliest dl and rq leftmost caching", cfq_rq->tasks_timeline type
changed from rb_root to rb_root_cached.

This patch will try rb_root, if failed then try rb_root_cached again to
avoid above exception.

Signed-off-by: Joe Jin <joe.jin@oracle.com>