dmshow: Add a check for mapped_device's UUID
In some of the vmcores, it was found that UUID embedded into the
mapped_device's hash_cell.uuid pointer is 0x0 or NULL. This would cause
failure in dmshow --lvs, --lvuuid and --pvs commands with following
traces:

crash> dmshow --lvs
...
Traceback (most recent call last):
  File "/cores/crashext/scsishow.so/progs/dmshow.py", line 557, in <module>
    show_multipath_list(dev)
  File "/cores/crashext/scsishow.so/progs/dmshow.py", line 302, in show_linear_lvm
    try:
TypeError: argument of type 'NoneType' is not iterable

This patch adds a check to verify if mapped_device is having valid UUID
else report the same to users:

For example:

+++WARNING+++ Invalid UUID for mapped_device: 0xffff8844096d9000 | hash_cell.uuid (UUID) is: None
+++WARNING+++ Invalid UUID for mapped_device: 0xffff88654319b400 | hash_cell.uuid (UUID) is: None