scsishow.py: add a check to verify gendisk struct
In some cases, custom multipathing solutions e.g. EMC PowerPath
manipulates the gendisk structure associated with SCSI devices.
This gendisk structure is not registered with kernel. Due to this,
processing gendisk strut in scsishow.py -q command could fail
with below error:

Traceback (most recent call last):
  File "/cores/crashext/scsishow.so/progs/scsishow.py", line 789, in <module>
  File "/cores/crashext/scsishow.so/progs/scsishow.py", line 365, in print_request_queue
UnboundLocalError: local variable 'gendev' referenced before assignment

This patch adds a check in print_request_queue function to
verify gendisk struct, before printing it. The other function
print_sdev_shost is not affected by above issue.